resolver: lts-10.3

packages:
- .
- posts
- posts/munge
- posts/arithmetic-made-difficult
- posts/software-tools-in-haskell
- posts/project-euler
- posts/ml
- posts/hs-notes

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- hakyll-shortcode-0.0.2
- cabal-doctest-1.0.2
- lispparser-0.3.1
- random-extras-0.19
- monad-primitive-0.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
